# Generated by Django 6.0.5 on 2026-06-27 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Производителя',
                'verbose_name_plural': 'Производители',
                'db_table': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Корзину',
                'verbose_name_plural': 'Корзины',
                'db_table': 'basket',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('designer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дизайнер')),
                ('status', models.CharField(choices=[('not started', 'не начат'), ('kitted', 'собран'), ('in progress', 'в работе'), ('complete', 'завершен')], default='not started', max_length=20, verbose_name='Статус')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Запас',
                'verbose_name_plural': 'Запасы',
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(db_index=True, max_length=50, verbose_name='Артикул')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, null=True, upload_to='threads_images/', verbose_name='Изображение')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Нитку',
                'verbose_name_plural': 'Нитки',
                'db_table': 'thread',
            },
        ),
        migrations.CreateModel(
            name='StockThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.stock', verbose_name='Запас')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.thread', verbose_name='Нитка')),
            ],
            options={
                'verbose_name': 'Запас - Нитка',
                'verbose_name_plural': 'Запасы - Нитки',
                'db_table': 'stock_thread',
            },
        ),
        migrations.CreateModel(
            name='ProjectThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.project', verbose_name='Проект')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.thread', verbose_name='Нитка')),
            ],
            options={
                'verbose_name': 'Проект - Нитка',
                'verbose_name_plural': 'Проекты - Нитки',
                'db_table': 'project_thread',
            },
        ),
        migrations.CreateModel(
            name='BasketThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.basket', verbose_name='Корзина')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.thread', verbose_name='Нитка')),
            ],
            options={
                'verbose_name': 'Корзину - Нитку',
                'verbose_name_plural': 'Корзины - Нитки',
                'db_table': 'basket_thread',
            },
        ),
        migrations.AddConstraint(
            model_name='thread',
            constraint=models.UniqueConstraint(fields=('article', 'manufacturer'), name='unique_thread_article_manufacturer'),
        ),
        migrations.AddConstraint(
            model_name='stockthread',
            constraint=models.UniqueConstraint(fields=('stock', 'thread'), name='unique_stock_thread'),
        ),
        migrations.AddConstraint(
            model_name='projectthread',
            constraint=models.UniqueConstraint(fields=('project', 'thread'), name='unique_project_thread'),
        ),
        migrations.AddConstraint(
            model_name='basketthread',
            constraint=models.UniqueConstraint(fields=('basket', 'thread'), name='unique_basket_thread'),
        ),
    ]
