# Generated by Django 6.0.5 on 2026-10-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='basketthread',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0.01)), name='basket_thread_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='projectthread',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0.01)), name='project_thread_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockthread',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0.01)), name='stock_thread_quantity_positive'),
        ),
    ]
